language: php
php:
  - 5.6
services:
  - mysql
install:
 - cp .env.testing.travis .env.testing
 - mysql -e 'create database if not exists test;'
 - composer self-update
 - composer install  --no-interaction
 - chmod -R 777 app/storage
 - php artisan migrate:install --env=testing --no-interaction -vvv
script:
 - ./vendor/bin/phpcs
 - php artisan migrate --env=testing --no-interaction -vvv
 - php artisan db:seed --env=testing --no-interaction -vvv
 - phpunit
 - php artisan migrate:rollback --env=testing --no-interaction -vvv
